[T] (quests) the_bees_it_stings
ShaBaiTianCN/Chroma-Endless pull request #10
Opened 2023-01-03 10:55 UTC by nai200

Co-authored-by: ForesT <qq15504746088@163.com>

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "蜜蜂棒棒能使蜜蜂和”花朵“链接"
```suggestion
			subtitle: "蜜蜂棒棒能使蜜蜂和“花朵”链接"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "蜂力怕"蜜蜂
```suggestion
			title: "蜂力怕蜜蜂"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 12:37 UTC, xinyihl commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 13:02 UTC, Cactusstudent requested changes
问题极大……审的……好费劲
PS：多的空格记得全删了

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +				"&6离心机&r试用RF能源将你的蜜脾变成资源。"
```suggestion
				"&6离心机&r消耗RF将你的蜜脾变成资源。"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "烈焰蜂"
```suggestion
			title: "烈焰蜜蜂"
```
这个翻译不太确定，没开游戏，仅供参考

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "粘土蜂"
```suggestion
			title: "黏土蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "末影史莱姆蜜蜂"
```suggestion
			title: "末影黏液蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "萤石蜂"
```suggestion
			title: "荧石蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "纯镥Bee"
？

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下届蜂"
```suggestion
			title: "下界蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下届石英蜂"
```suggestion
			title: "下界石英蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下届蜂"
```suggestion
			title: "下界蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "马玉灵蜜蜂"
```suggestion
			title: "玛玉灵蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下届水晶蜜蜂"
```suggestion
			title: "下界晶体蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "钻石水晶蜜蜂"
```suggestion
			title: "钻石晶体蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "强化萤石蜂"
```suggestion
			title: "强化荧石蜜蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "史莱姆蜂"
```suggestion
			title: "黏液蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "碧空史莱姆蜂"
```suggestion
			title: "碧空黏液蜂"
```

2023-01-03 13:02 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "Xion 蜂"
？

2023-01-03 18:51 UTC, Ricky-fight requested changes
问题比较多

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "地狱蜂巢"
```suggestion
			title: "下界蜂巢"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "ATMBee"
```suggestion
			title: "ATM蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "ATMBee"
```suggestion
			title: "ATM蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "太古合金蜂"
```suggestion
			title: "太古合金蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "粘土蜂"
```suggestion
			title: "黏土蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "青铜蜂"
```suggestion
			title: "青铜蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "黄铜蜂"
```suggestion
			title: "黄铜蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "龙蜂"
```suggestion
			title: "龙蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "龙矿蜂"
这得开游戏看看是不是龙矿，Productive Bees里是龙锭蜜蜂，产龙锭
```suggestion
			title: "龙矿蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "铜蜂"
```suggestion
			title: "铜蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "压缩铁蜂"
```suggestion
			title: "压缩铁蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "钴蜂"
```suggestion
			title: "钴蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "煤蜂"
```suggestion
			title: "煤蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "源质蜂"
```suggestion
			title: "源质钢蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "琥珀金蜂"
```suggestion
			title: "琥珀金蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "浸透铁蜂"
```suggestion
			title: "浸透铁蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "火焰合金蜂"
```suggestion
			title: "火焰合金蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "仙女蜂"
```suggestion
			title: "仙女蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "灵浆Bee"
```suggestion
			title: "灵浆蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "守卫者蜂"
```suggestion
			title: "守卫者蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "沙砾蜂"
```suggestion
			title: "沙砾蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "纯镥Bee"
```suggestion
			title: "镠蜜蜂"
```
极限反应堆里的

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "铅蜂"
```suggestion
			title: "铅蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "铁蜂"
```suggestion
			title: "铁蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "殷钢蜂"
```suggestion
			title: "殷钢蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "镍蜂"
```suggestion
			title: "镍蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "磁铁矿蜂"
```suggestion
			title: "品红蜜蜂"
```
可能是极限反应堆里的Magentite反应物，得开游戏实测，这里先写下suggestion了

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "硝酸钾蜂"
```suggestion
			title: "硝酸钾蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "在下届生成"
```suggestion
			subtitle: "在下界生成"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "锇蜂"
```suggestion
			title: "锇蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "沙蜂"
```suggestion
			title: "沙蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "沉积蜜蜂"
```suggestion
			title: "悖谬蜜蜂"
```
极限反应堆里的

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "贵豪蜂"
```suggestion
			title: "贵豪蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "强化黑曜石蜂"
```suggestion
			title: "强化黑曜石蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "红石蜂"
```suggestion
			title: "红石蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "灵魂熔岩蜂"
```suggestion
			title: "灵魂熔岩蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "银蜂"
```suggestion
			title: "银蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "信素蜂"
```suggestion
			title: "信素蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "锡蜂"
```suggestion
			title: "锡蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "铊蜂"
```suggestion
			title: "铊蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "终界蜂"
```suggestion
			title: "终界蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: ""查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: ""查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "石蜂"
```suggestion
			title: "石头蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "钢铁蜜蜂"
```suggestion
			title: "钢蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "锌蜂"
```suggestion
			title: "锌蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "雪人蜂"
```suggestion
			title: "雪人蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "Xion 蜂"
```suggestion
			title: "Xion蜜蜂"
```
先放着吧，查了下是Tardis的Xion Crystal，目前还没翻译

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "水蜂"
```suggestion
			title: "水蜜蜂"
```
这也有蜜蜂……

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "振金蜂"
```suggestion
			title: "振金蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "铀蜂"
```suggestion
			title: "铀蜜蜂"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 18:51 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 19:56 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			subtitle: "查看 &4蜂罐&r 的合成表"
```suggestion
			subtitle: "查看&4蜂罐&r的合成表"
```

2023-01-03 20:01 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "闪电蜂"
```suggestion
			title: "闪电蜜蜂"
```

2023-01-03 20:03 UTC, AnzhiZhang commented
还有三个小问题，需要开游戏

2023-01-03 21:15 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "龙矿蜂"
游戏实测产龙粒，确认更改为`龙锭蜜蜂`

2023-01-03 21:16 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "磁铁矿蜂"
确认为极限反应堆的联动，为`品红蜜蜂`

2023-01-03 21:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "沉积蜜蜂"
确认为极限反应堆的联动，为`悖谬蜜蜂`

2023-01-03 21:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "Xion 蜂"
![image](https://user-images.githubusercontent.com/13982778/210443026-e26c8fb7-6c73-4549-8df3-0c227e2dd705.png)

2023-01-06 11:36 UTC, AnzhiZhang approved these changes

2023-01-06 11:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "离心控制器级别1"
不用生硬翻译成级别
```suggestion
			title: "离心控制器T1"
```

2023-01-06 11:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "离心控制器级别2"
```suggestion
			title: "离心控制器T2"
```

2023-01-06 11:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "离心控制器级别3"
```suggestion
			title: "离心控制器T3"
```

2023-01-06 11:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "离心控制器级别4"
```suggestion
			title: "离心控制器T4"
```

2023-01-06 11:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "离心控制器级别5"
```suggestion
			title: "离心控制器T5"
```

2023-01-09 21:37 UTC, AnzhiZhang approved these changes

2023-01-10 16:38 UTC, Ricky-fight approved these changes
改完这些应该差不多了

2023-01-10 16:38 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "煤蜜蜂"
```suggestion
			title: "煤炭蜜蜂"
```

2023-01-10 16:38 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下界蜜蜂"
```suggestion
			title: "下界合金蜜蜂"
```
游戏里是下界合金蜜蜂

2023-01-10 16:38 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "下界蜂"
```suggestion
			title: "下界蜜蜂"
```

2023-01-10 16:38 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/the_bees_it_stings.snbt
> +			title: "沙蜜蜂"
```suggestion
			title: "沙子蜜蜂"
```

2023-01-10 21:07 UTC, merged