[T] (quests) botania
ShaBaiTianCN/Chroma-Endless pull request #17
Opened 2023-01-05 12:16 UTC by nai200

Co-authored-by: 墨羽千寻 <169262849@qq.com>

2023-01-05 12:41 UTC, Cactusstudent requested changes
emm，量挺大

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"从&aMana&r和&a石头&r中创造原矿的能力对任何植物学家来说都是一个巨大的福音。"
```suggestion
				"用&a魔力&r和&a石头&r创造原矿的能力对任何植物学家来说都是一个巨大的福音。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["它会吸收掉在附近的任何可燃物品或方块，一次一个，并燃烧它们产生&aMana&r。"]
```suggestion
			description: ["它会吸收掉在附近的任何可燃物品或方块，一次一个，并燃烧它们产生&a魔力&r。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"最后，为了吸收爆炸，花朵本身需要无&aMana&r，否则吸收将会失败。"
```suggestion
				"最后，为了吸收爆炸，花朵本身需要无&a魔力&r，否则吸收将会失败。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"靠近热爆花点燃一个&dTNT&r，&d热爆花&r就会吸收爆炸产生的热和冲击并产生大量的&aMana&r消除一切爆炸伤害。"
```suggestion
				"靠近热爆花点燃一个&dTNT&r，&d热爆花&r就会吸收爆炸产生的热和冲击并产生大量的&a魔力&r消除一切爆炸伤害。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&aMana&r的产量也会因营养而异，&d彼方兰&r更喜欢保持度多的食物。"
```suggestion
				"&a魔力&r的产量也会因营养而异，&d彼方兰&r更喜欢保持度多的食物。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["&d贪食花&r就是这些&d蛋糕&r的狂热爱好者之一，他们会吃任何放置在它附近的蛋糕，将丰富的营养合成成甜甜的&aMana&r。"]
```suggestion
			description: ["&d贪食花&r就是这些&d蛋糕&r的狂热爱好者之一，他们会吃任何放置在它附近的蛋糕，将丰富的营养合成成甜甜的&a魔力&r。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&a史莱姆&r越大，其产生的&aMana&r越多。（这也造成了一些黏乎乎的麻烦。）"
```suggestion
				"&a史莱姆&r越大，其产生的&a魔力&r越多。（这也造成了一些黏乎乎的麻烦。）"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["它会寻找附近放置的所有花朵并消耗掉，并以此产生&aMana&r。连续几次投喂同一种花的收益递减，而投喂大量不同种类的花可以产生大量的&aMana&r。"]
```suggestion
			description: ["它会寻找附近放置的所有花朵并消耗掉，并以此产生&a魔力&r。连续几次投喂同一种花的收益递减，而投喂大量不同种类的花可以产生大量的&a魔力&r。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["它将吸收任何掉落在它附近的&d羊毛&r，将它们转换为&aMana&r。然而，它对颜色十分挑剔。从&b白色&r开始，吸收一块&b羊毛&r后，它会按照顺序所求下一个颜色的羊毛。"]
```suggestion
			description: ["它将吸收任何掉落在它附近的&d羊毛&r，将它们转换为&a魔力&r。然而，它对颜色十分挑剔。从&b白色&r开始，吸收一块&b羊毛&r后，它会按照顺序所求下一个颜色的羊毛。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"凝矿兰使用&aMana&r将附近的&b石头&r块转化为&a矿物&r。"
```suggestion
				"凝矿兰消耗&a魔力&r将附近的&b石头&r块转化为&a矿物&r。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"这个过程使用了相当数量的&aMana&r，但不会耗尽整个库存（或池）。"
```suggestion
				"这个过程使用了相当数量的&a魔力&r，但不会耗尽整个库存（或池）。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"当被喂食相当多的&aMana&r时，&d聚宝花&r可以使地牢里的奖励成为可收集的物品。不过，有一个陷阱。除了这个物品外，还有一个怪物被用来保护它。"
```suggestion
				"当被喂食相当多的&a魔力&r时，&d聚宝花&r可以使地牢里的奖励成为可收集的物品。不过，有一个陷阱。除了这个物品外，还有一个怪物被用来保护它。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["&d咀叶花&r将吃掉附近的任何&d树叶&r，并将它们转化为&aMana&r。但是，不会有树苗（或任何其他物品）从叶子里掉出来。"]
```suggestion
			description: ["&d咀叶花&r将吃掉附近的任何&d树叶&r，并将它们转化为&a魔力&r。但是，不会有树苗（或任何其他物品）从叶子里掉出来。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "产生自然能量，即Mana，的最佳方式是从其他生物材料中提取。"
```suggestion
			subtitle: "产生自然能量，即魔力，的最佳方式是从其他生物材料中提取。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&aMana&r不是必要的，但如果提供将增加其范围。将&d物品展示框&r放置在相邻的存储容器中将指定哪些项目可以或不可以放入其中。"
```suggestion
				"&aM魔力&r不是必要的，但如果提供将增加其范围。将&d物品展示框&r放置在相邻的存储容器中将指定哪些物品可以或不可以放入其中。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "在沙坑里找到的?"
```suggestion
			subtitle: "在沙坑里找到的？"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["田园康乃馨将&aMana&r转化为一种天然肥料，使附近的植物生长得更快。"]
```suggestion
			description: ["田园康乃馨将&a魔力&r转化为一种天然肥料，使附近的植物生长得更快。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"它们会吸收周围3x3区域内的&d静止的水&r（在同一高度），并将水转化为&aMana&r。"
```suggestion
				"它们会吸收周围3x3区域内的&d静止的水&r（在同一高度），并将水转化为&a魔力&r。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"不幸的是，尽管他们在&a雨天&r期间似乎运行得更快，但他们的基础&aMana&r吞吐量仍然相当少。此外，他们会在大约3天后腐烂，使他们无法长期生产魔力。"
```suggestion
				"不幸的是，尽管他们在&a雨天&r期间似乎运行得更快，但他们的基础&a魔力&r吞吐量仍然相当少。此外，他们会在大约3天后腐烂，使他们无法长期生产魔力。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&a多媒体&r系统是一个利用&a末地&r的能量和世界的空白空间，将物品从A点瞬间到B点，无需任何连接部件。这个系统通过&5火花&r的变种来运作（称为&5多媒体火花&r），它们运输物品而不是&aMana&r。"
```suggestion
				"&a多媒体&r系统是一个利用&a末地&r的能量和世界的空白空间，将物品从A点瞬间到B点，无需任何连接部件。这个系统通过&5火花&r的变种来运作（称为&5多媒体火花&r），它们运输物品而不是&a魔力&r。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"使用&5魔力发射器&r来传输&aMana&r是不错的选择，但也有其他方法做到这件事。"
```suggestion
				"使用&5魔力发射器&r来传输&a物品&r是不错的选择，但也有其他方法做到这件事。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5魔力石板&r是个重要的物品，用来存储&aMana&r到它自己里。"
```suggestion
				"&5魔力石板&r是个重要的物品，用来存储&a物品&r到它自己里。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"将一个石板扔进一个&5魔力池&r，将允许在他们之间流动&aMana&r。"
```suggestion
				"将一个石板扔进一个&5魔力池&r，将允许&a魔力&r在他们之间流动。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5魔力发射器&r有一个小的内部&aMana&r缓冲，会被绑定它的&a产能花&r填充。（当花放置时，自动绑定到最近的发射器。）"
```suggestion
				"&5魔力发射器&r有一个小的内部&a魔力&r缓冲，会被绑定它的&a产能花&r填充。（当花放置时，自动绑定到最近的发射器。）"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"这个方块将&aMana&r从A点射到b点。当放置时，它面对一个基本的方向，但是用一个&5森林法杖&r在一个面上右键点击它，将它指向其他地方。可以用在&a绑定模式&r的森林法杖将它瞄准向其他方块。"
```suggestion
				"这个方块将&a魔力&r从A点射到b点。当放置时，它面对一个基本的方向，但是用一个&5森林法杖&r在一个面上右键点击它，将它指向其他地方。可以用在&a绑定模式&r的森林法杖将它瞄准向其他方块。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5魔力发射器&r是植物学家需要的最重要的用来传输&aMana&r的工具。"
```suggestion
				"&5魔力发射器&r是植物学家需要的最重要的用来传输&a魔力&r的工具。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5植物魔法词典&r是所有植物学知识的宝库。"
```suggestion
				"&5植物魔法辞典&r是所有植物学知识的宝库。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"所有著名的植物学知识都储存在这些页面中。为了方便起见，如果一个方块恰好在里面有一个条目，可以拿着&5植物魔法词典&r按住潜行键，右键点击它来打开该条目。"
```suggestion
				"所有著名的植物学知识都储存在这些页面中。为了方便起见，如果一个方块恰好在里面有一个条目，可以拿着&5植物魔法辞典&r按住潜行键，右键点击它来打开该条目。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["有一种难以发现的花，名叫&5黑莲花&r； 然而，它不能生长或繁殖。目前还没有这种莲花的已知来源。但是，我们知道，每一朵花都含有大量的浓缩的&aMana&r可以通过溶解在一个非空的&5魔力池&r中释放出来。把它扔进去就行了。"]
```suggestion
			description: ["有一种难以发现的花，名叫&5黑莲花&r； 然而，它不能生长或繁殖。目前还没有这种莲花的已知来源。但是，我们知道，每一朵花都含有大量的浓缩的&a魔力&r，可以通过溶解在一个非空的&5魔力池&r中释放出来。把它扔进去就行了。"]
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5弥散升级&r允许&5火花&r耗尽魔力池里的&aMana&r给附近玩家的&aMana&r储存工具充能。"
```suggestion
				"&5弥散升级&r允许&5火花&r耗尽魔力池里的&a魔力&r给附近玩家的&a魔力&r储存工具充能。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5聚集升级&r允许&5火花&r从附近的装有未升级的或装有弥散升级的&5火花&r的魔力池汲取&aMana&r到本身的魔力池中。直到本身的魔力池变满。"
```suggestion
				"&5聚集升级&r允许&5火花&r从附近的装有未升级的或装有弥散升级的&5火花&r的魔力池汲取&a魔力&r到本身的魔力池中。直到本身的魔力池变满。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5扩散升级&r允许&5火花&r分发&aMana&r到装有未升级或装有弥散升级的&5火花&r的魔力池之中。直到本身的魔力池完全变空。"
```suggestion
				"&5扩散升级&r允许&5火花&r分发&a魔力&r到装有未升级或装有弥散升级的&5火花&r的魔力池之中。直到本身的魔力池完全变空。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"最后，&5隔绝升级&r阻止&5火花&r与带有扩散或者聚集升级的&5火花&r魔力池交互魔力，但是仍然允许它和可以从&5火花&r网络接收&aMana&r的方块交互。"
```suggestion
				"最后，&5隔绝升级&r阻止&5火花&r与带有扩散或者聚集升级的&5火花&r魔力池交互魔力，但是仍然允许它和可以从&5火花&r网络接收&a魔力&r的方块交互。"
```

2023-01-05 12:41 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +				"&5火花&r是有趣的东西啊。用原始的能量和&aMana&r制造，它们只能被放置在一些特定的能够存储&aMana&r或者接收&aMana&r的方块上（例如&5魔力池&r）。"
```suggestion
				"&5火花&r是有趣的东西啊。用原始的能量和&a魔力&r制造，它们只能被放置在一些特定的能够存储&a魔力&r或者接收&a魔力&r的方块上（例如&5魔力池&r）。"
```

2023-01-05 17:43 UTC, Ricky-fight approved these changes

2023-01-05 17:43 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "炎矿兰是一朵很好的花"
```suggestion
			subtitle: "凝矿兰是一朵很好的花"
```

2023-01-05 17:43 UTC, Ricky-fight approved these changes

2023-01-06 11:34 UTC, AnzhiZhang approved these changes

2023-01-06 11:34 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			title: "活石台阶"
为什么多了个标题

2023-01-06 11:34 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["不。真的，就是这样。一个&5土豆&r，扔进&5魔力池&r，迸发出生命与愉悦的火花&5小土豆&r是活着的，但用右键点击它会使它更加活泼!土豆也可以命名为&5Anvil&r。"]
Anvil

2023-01-06 11:34 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"用&5森林法杖&r在&5魔力池&r上用鼠标右键点击（或者使用&5发射器&r）将会改变&aMana&r的流向。"
```suggestion
				"用&5森林法杖&r在&5魔力池&r上用鼠标右键点击（或者使用&5发射器&r）将会改变&a魔力&r的流向。"
```

2023-01-09 21:35 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			title: "活石台阶"
```suggestion
```

2023-01-09 21:36 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["不。真的，就是这样。一个&5土豆&r，扔进&5魔力池&r，迸发出生命与愉悦的火花&5小土豆&r是活着的，但用右键点击它会使它更加活泼!土豆也可以命名为&5Anvil&r。"]
```suggestion
			description: ["不。真的，就是这样。一个&5土豆&r，扔进&5魔力池&r，迸发出生命与愉悦的火花&5小土豆&r是活着的，但用右键点击它会使它更加活泼!土豆也可以在&5铁砧&r中重命名。"]
```

2023-01-09 21:36 UTC, AnzhiZhang approved these changes

2023-01-09 21:37 UTC, merged