[T] (quests) chaptre_1
ShaBaiTianCN/Chroma-Endless pull request #31
Opened 2023-01-12 07:44 UTC by nai200

Co-authored-by: lailai <m18721693124@163.com>
Co-authored-by: 藏青 <2291848664@qq.com>
Co-authored-by: 海福 <18917570841@163.com>

2023-01-12 09:30 UTC, Ricky-fight requested changes
300

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +	title: "&b第一章&r&6-&r入门"
```suggestion
	title: "&b第一章&r&6-&r新的开始"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "首先:&#806517木头&r"
```suggestion
			title: "一切的起点：&#806517原木&r"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			subtitle: "砍树时间"
```suggestion
			subtitle: "砍树时间！"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"砍树收集&#806517木头&r（任何&#806517木头&r都可以）。"
```suggestion
				"砍树收集&#806517原木&r（任何&#806517原木&r都可以）。"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"专业提示：不要忘记连锁"
```suggestion
				"专业提示：不要忘记连锁！"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "寻找: &#5F6366燧石&r"
```suggestion
			title: "寻找：&#5F6366燧石&r"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "工作台"
```suggestion
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			subtitle: "几乎一切的开始"
此处再想想

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"为了3*3挖掘能力，必须应用为双头工具的第二个头"
```suggestion
				"为了能3*3挖掘，一个双头工具需要装上地底提取器作为第二个头部配件"
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "翻箱子"
```suggestion
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"凿地器可以赋予单头工具镐子的能力（即左键长按可破坏石质类方块），装配轻手柄后投掷可一次破坏直线5格的石质类方块（从起始方块向里挖掘，受到效率附魔、打磨与攻击速度加成）。"
？

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "燃烧室"
```suggestion
```

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"将锤子链接在燃烧室上，使锤力层数增加1。"
游戏里是怎么操作的？从语法上这个主宾肯定反了，attach具体翻译成什么词看实际游戏内容

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"-热能锻锤正常工作需要在侧面安装2个热电池（正方形口）及2个插件（长方形口），并在下方空一格处放置一个锻造工作台。"
这又是从哪里抄来的

2023-01-12 09:30 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"-锻锤工作完毕后会有几率卡住，需要持4级或以上的锤子右击锻锤头部下沿进行修复。"
1

2023-01-12 09:30 UTC, Ricky-fight commented
看不下去了，换个人来吧

2023-01-12 11:26 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			subtitle: "几乎一切的开始"
考虑到是原版的工作台
```suggestion
			subtitle: "万物之源"
```
```suggestion
			subtitle: "梦开始的地方"
```

2023-01-12 11:27 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"凿地器可以赋予单头工具镐子的能力（即左键长按可破坏石质类方块），装配轻手柄后投掷可一次破坏直线5格的石质类方块（从起始方块向里挖掘，受到效率附魔、打磨与攻击速度加成）。"
麻烦核对下工具名，估计旧版任务
```suggestion
				"凿地器是一种多合一工具（镐子和锹）。"
```

2023-01-12 12:46 UTC, Cactusstudent reviewed
标点符号需要有人再过一遍，我是看完了

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				title: "黑曜石锤"
```suggestion
				title: "黑曜石锤子"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"使用升级的锻造台锤制作黑曜石锤，黑曜石锤提供第五级锤力"
```suggestion
				"使用一台升级了的锻造锤制作一把双头黑曜石锤子，黑曜石锤子提供5级的锤击功能"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "五级锤力"
```suggestion
			title: "锤子 V（黑曜石）"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "六级锤力"
```suggestion
			title: "锤子 VI（下界合金）"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			description: ["使用完全升级的锻造台锤制作下界合金锤，下界合金锤提供第六层锤力。"]
```suggestion
			description: ["使用一台完全升级的锻造锤制作一把双头下界合金锤子，下界合金锤子提供6级的锤击功能"]
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				title: "下界合金锤"
```suggestion
				title: "下界合金锤子"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "四级锤力"
```suggestion
			title: "锤子 IV（黑石）"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"制作黑石锤，黑石锤提供四级锤力。"
```suggestion
				"制作一把双头黑石锤子，黑石锤子提供4级的锤击功能"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				title: "黑石锤"
```suggestion
				title: "黑石锤子"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"升级后的手柄或捆绑件将提供足够的完整性来支撑黑石锤。"
```suggestion
				"一个升级的手柄或一个绑定能提供黑石锤子所需的完整度。"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "二级锤力"
```suggestion
			title: "锤子 II（石）"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			description: ["将您的锤子升级为石锤（任何类型的石头），石锤提供第二级锤力。"]
```suggestion
			description: ["将锤子升级到双头石锤（可用任意类型的石头），石锤子提供2级的锤击功能"]
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				title: "一级锤力"
```suggestion
				title: "锤子 I（木）"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				title: "石头锤"
```suggestion
				title: "石头锤子"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "木镐"
这里是多的？

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "&#806517木镐&r 配件"
```suggestion
			title: "&#806517木 镐&r 配件"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +					title: "&#806517木镐&r头"
```suggestion
					title: "&#806517木 镐&r头"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +					title: "&#806517木&r工具手柄"
```suggestion
					title: "&#806517木&r 工具手柄"
```
这些改的全是匠魂特色，中间空格（）

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +					title: "&#806517木&r绑定结"
```suggestion
					title: "&#806517木&r 绑定结"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"以下任务向您展示了您在&2主世界&r。上可以找到的矿石"
```suggestion
				"以下任务向您展示了在&2主世界&r可以找到的矿石。"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			subtitle: "&#D52B1E就像McDonald's®（麦当劳）&r快餐一样"
```suggestion
			subtitle: "就像&#D52B1EMcDonald's®（麦当劳）&r快餐一样"
```

2023-01-12 12:46 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			description: ["&6任何海洋生物群系, Y=5 - 45 层"]
```suggestion
			description: ["&6任何海洋生物群系，Y=5-45层"]
```

2023-01-12 12:53 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "匠魂工具或tetra"
```suggestion
			title: "匠魂和Tetra"
```

2023-01-12 12:54 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "木镐"
```suggestion
```

2023-01-12 13:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"将原版&#806517木镐&r放入加工台"
```suggestion
				"将你之前做好的原版&#806517木镐&r放入加工台"
```

2023-01-12 13:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"把木镐放入加工台后可修改配件，修改为木头配件可变为59耐久"
```suggestion
				"再点击&o“修复”&r并在槽位栏放上一个木板。"
```

2023-01-12 13:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
>  				""
```suggestion
				""
				"如果你有一把&#806517木斧&r（或其它1级斧）在你的物品栏里，你就可以点击&o“制作”&r。"
```

2023-01-12 13:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
>  				""
```suggestion
				""
				"你的原版&#806517木镐&r现在已经是一把Tetra&#806517木镐&r了，并且有59点耐久度。"
```

2023-01-12 13:18 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			description: ["烟熏炉工作起来像熔炉一样，但是是能做食物，速度是熔炉的一倍"]
```suggestion
			description: ["烟熏炉工作起来像熔炉一样，但是是能烹饪食物，速度是熔炉的两倍"]
```

2023-01-12 13:31 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"将锤子链接在燃烧室上，使锤力层数增加1。"
```suggestion
				"燃烧室可以被连接到锻造锤上，可将锤子的等级提升1"
```

2023-01-12 13:34 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"-热能锻锤正常工作需要在侧面安装2个热电池（正方形口）及2个插件（长方形口），并在下方空一格处放置一个锻造工作台。"
```suggestion
				"-将两个热力单元和两个升级（燃烧室和平面稳定器）连接到一把锻造锤上来修复它。"
```

2023-01-12 13:37 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"-锻锤工作完毕后会有几率卡住，需要持4级或以上的锤子右击锻锤头部下沿进行修复。"
```suggestion
				"-使用羊角头从锻造锤上拆下一个升级。"
```

2023-01-12 13:38 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
>  				""
是制作

2023-01-15 09:44 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "木镐"
```suggestion
```

2023-01-15 09:46 UTC, AnzhiZhang approved these changes

2023-01-15 10:03 UTC, Ricky-fight requested changes

2023-01-15 10:03 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"有三类&7&c（这里的颜色与下面任务颜色的挖掘等级对应）："
```suggestion
				"有以下三类："
```

2023-01-15 10:03 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"   -可使用&6木镐&r或其他具有同等开采水平的镐开采的矿石。"
```suggestion
				"   -可使用&6木镐&r或其他具有同等采掘等级的镐开采的矿石。"
```

2023-01-15 10:03 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"   -可使用&5石镐&r或其他具有同等开采水平的镐开采的矿石。"
```suggestion
				"   -可使用&5石镐&r或其他具有同等采掘等级的镐开采的矿石。"
```

2023-01-15 10:03 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +				"   -可使用&b铁镐&r或其他具有同等开采水平的镐开采的矿石。"
```suggestion
				"   -可使用&b铁镐&r或其他具有同等采掘等级的镐开采的矿石。"
```

2023-01-15 10:03 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/chaptre_1.snbt
> +			title: "如何得到它"
```suggestion
```

2023-01-15 10:05 UTC, merged